version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "./"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "./example/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
